require "rails_helper"

RSpec.describe Employee do
  describe "associations" do
    it { is_expected.to have_many(:salaries).dependent(:delete_all) }
    it { is_expected.to belong_to(:fx_rate).optional }
  end

  describe "validations" do
    subject(:employee) { build(:employee) }

    it { is_expected.to be_valid }
    it { is_expected.to validate_presence_of(:first_name) }
    it { is_expected.to validate_presence_of(:last_name) }
    it { is_expected.to validate_length_of(:first_name).is_at_most(Employee::NAME_MAX_LENGTH) }
    it { is_expected.to validate_presence_of(:email) }
    it { is_expected.not_to allow_value("not-an-email").for(:email) }
    it { is_expected.to validate_presence_of(:hire_date) }
    it { is_expected.to validate_numericality_of(:current_salary_cents).only_integer.is_greater_than(0) }

    it "requires a unique email regardless of case" do
      create(:employee, email: "ada@acme.test")

      expect(validation_errors(build(:employee, email: "ADA@acme.test"), :email)).to include("has already been taken")
    end

    it "rejects an unsupported country" do
      employee.country = "FR"

      expect(validation_errors(employee, :country)).to include("is not included in the list")
    end

    it "reports a blank country and department as missing rather than unsupported" do
      employee.assign_attributes(country: "", department: "")

      expect(validation_errors(employee, :country)).to eq([ "can't be blank" ])
      expect(validation_errors(employee, :department)).to eq([ "can't be blank" ])
    end

    it "rejects an unknown department" do
      employee.department = "Legal"

      expect(validation_errors(employee, :department)).to include("is not included in the list")
    end

    it "rejects a job title from another department" do
      employee.job_title = "Account Executive"

      expect(validation_errors(employee, :job_title)).to include("is not a job title in Engineering")
    end

    it "rejects a currency that does not match the country" do
      employee.assign_attributes(country: "DE", current_salary_currency: "USD")

      expect(validation_errors(employee, :current_salary_currency)).to include("must be EUR for this country")
    end

    it "rejects a hire date in the future" do
      travel_to(Date.new(2026, 1, 10)) do
        employee.hire_date = Date.new(2026, 1, 11)

        expect(validation_errors(employee, :hire_date)).to include("can't be in the future")
      end
    end
  end

  describe "normalization" do
    it "strips and downcases email and upcases codes" do
      employee = build(:employee, email: "  Ada@ACME.test ", country: " gb ", current_salary_currency: "gbp")

      expect(employee).to have_attributes(email: "ada@acme.test", country: "GB", current_salary_currency: "GBP")
    end

    it "squishes whitespace in names and titles" do
      expect(build(:employee, first_name: "  Ada   Mary ").first_name).to eq("Ada Mary")
    end
  end

  describe "employee_code" do
    it "is generated by the database from the id" do
      employee = create(:employee)

      expect(employee.employee_code).to eq(format("ACME-%06d", employee.id))
    end
  end

  describe "#current_salary" do
    it "returns the cached salary as Money" do
      employee = build(:employee, country: "IN", current_salary_cents: 25_00_000_00)

      expect(employee.current_salary).to eq(Money.new(cents: 25_00_000_00, currency: "INR"))
    end

    it "is nil when no salary has been set" do
      expect(build(:employee, current_salary_cents: nil).current_salary).to be_nil
    end
  end

  describe "#full_name" do
    it "joins first and last name" do
      expect(build(:employee, first_name: "Ada", last_name: "Lovelace").full_name).to eq("Ada Lovelace")
    end
  end

  describe "scopes" do
    let!(:us_engineer) do
      create(:employee, country: "US", department: "Engineering", job_title: "Software Engineer I",
                        first_name: "Grace", last_name: "Hopper", email: "grace@acme.test")
    end
    let!(:in_sales) do
      create(:employee, country: "IN", department: "Sales", job_title: "Account Executive",
                        first_name: "Ravi", last_name: "Kumar", email: "ravi@acme.test")
    end

    describe ".in_country" do
      it "keeps employees in the given country, case-insensitively" do
        expect(described_class.in_country("in")).to contain_exactly(in_sales)
      end

      it "is a no-op when blank" do
        expect(described_class.in_country(nil)).to contain_exactly(us_engineer, in_sales)
      end
    end

    describe ".in_department" do
      it "keeps employees in the department" do
        expect(described_class.in_department("Engineering")).to contain_exactly(us_engineer)
      end

      it "is a no-op when blank" do
        expect(described_class.in_department("")).to contain_exactly(us_engineer, in_sales)
      end
    end

    describe ".with_job_title" do
      it "keeps employees with the exact title" do
        expect(described_class.with_job_title("Account Executive")).to contain_exactly(in_sales)
      end

      it "is a no-op when blank" do
        expect(described_class.with_job_title(nil)).to contain_exactly(us_engineer, in_sales)
      end
    end

    describe ".search" do
      it "matches a partial name case-insensitively" do
        expect(described_class.search("HOPP")).to contain_exactly(us_engineer)
      end

      it "matches across first and last name" do
        expect(described_class.search("ravi kum")).to contain_exactly(in_sales)
      end

      it "matches email and employee code" do
        expect(described_class.search("grace@")).to contain_exactly(us_engineer)
        expect(described_class.search(in_sales.employee_code)).to contain_exactly(in_sales)
      end

      it "treats LIKE wildcards in the term literally" do
        expect(described_class.search("%")).to be_empty
      end

      it "is a no-op when blank" do
        expect(described_class.search("  ")).to contain_exactly(us_engineer, in_sales)
      end
    end

    describe "chaining" do
      it "combines filters" do
        expect(described_class.in_country("US").in_department("Engineering").search("grace"))
          .to contain_exactly(us_engineer)
      end
    end

    describe ".with_usd_salary" do
      before { create(:fx_rate, currency: "INR", usd_per_unit: BigDecimal("0.012")) }

      it "adds the current salary converted to USD cents" do
        in_sales.update!(current_salary_cents: 20_00_000_00)

        expect(described_class.with_usd_salary.find(in_sales.id).current_salary_usd_cents).to eq(24_000_00)
      end

      it "is nil on records loaded without the scope" do
        expect(described_class.find(in_sales.id).current_salary_usd_cents).to be_nil
      end

      it "keeps employees whose currency has no rate, with a nil USD value" do
        expect(described_class.with_usd_salary.find(us_engineer.id).current_salary_usd_cents).to be_nil
      end
    end
  end

  describe "database constraints" do
    it "rejects a non-positive salary cache even when validations are bypassed" do
      employee = create(:employee)

      expect { employee.update_column(:current_salary_cents, 0) }
        .to raise_error(ActiveRecord::StatementInvalid, /employees_current_salary_positive/)
    end
  end
end
